### ISSUE TITLE
Having problems with code

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/more-than-just-datum#1]
I cannot separate my table contents from each other, I placed a gutter but it didn't work.

@thomasjbradley

**Comment by thomasjbradley** [comment]
I’m not entirely sure what you mean. Separate what table contents from what..?

**Comment by fuen0015** [comment]
![54728701_424203195053219_4439086645899165696_n](https://user-images.githubusercontent.com/43240727/54945091-6c329680-4f0b-11e9-9d19-3e2fee123a49.png)
Each other

**Comment by thomasjbradley** [comment]
Add a `min-width` to the `.table-wrapper`

**Comment by fuen0015** [comment]
I added the min-width but nothing changed, do I need to add padding?

**Comment by thomasjbradley** [comment]
How big is the `min-width`?

**Comment by fuen0015** [comment]
I tried 950px, it looks okay hopefully markbot will be happy but is this what we need to do?

**Comment by thomasjbradley** [comment]
Why `px`? Aren’t we measuring a distance of text?

**Comment by fuen0015** [comment]
oh yes whoops let me try 45em instead

**Comment by fuen0015** [comment]
I need to flex my two bottom grids but I am having trouble placing them side by side for the medium
<img width="816" alt="Screen Shot 2019-03-26 at 8 31 33 AM" src="https://user-images.githubusercontent.com/43240727/54997225-a3538700-4fa1-11e9-93a7-5c82685ab8d6.png">

**Comment by thomasjbradley** [comment]
The grid isn’t quite set up to create the layout we want. There should only be 2 units in the lower section:

1. 1 unit for the left side, the closest parks list
2. 1 unit that surrounds all the table data

These two unit should be within the same grid.

**Comment by fuen0015** [comment]
Can I come to your office to go over this?

**Comment by thomasjbradley** [comment]
Yep.

**Comment by fuen0015** [comment]
Just a few last things
Markbot is asking for this
<img width="442" alt="Screen Shot 2019-03-27 at 2 42 26 PM" src="https://user-images.githubusercontent.com/43240727/55103366-a7190380-509e-11e9-8fa0-2677c6808878.png">
Also I need my km to go to the side
<img width="320" alt="Screen Shot 2019-03-27 at 2 42 46 PM" src="https://user-images.githubusercontent.com/43240727/55103413-bac46a00-509e-11e9-81bf-cc2e826b3c9d.png">
but how can I?

**Comment by thomasjbradley** [comment]
For the missing text: both the `<img>` tags have empty `alt` attributes.

The other question, can’t help with right now because the code hasn’t been committed & pushed recently.

**Comment by fuen0015** [comment]
Sorry about that, you should be able to see it now

**Comment by fuen0015** [comment]
nevermind figured out thank you
